language: groovy
sudo: false
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
env:
  - GRADLE=gradle/gradle1.12/gradlew
  - GRADLE=gradle/gradle2.0/gradlew
  - GRADLE=gradle/gradle2.1/gradlew
  - GRADLE=gradle/gradle2.2.1/gradlew
  - GRADLE=gradle/gradle2.3/gradlew
  - GRADLE=gradle/gradle2.4/gradlew
  - GRADLE=gradle/gradle2.5/gradlew
install: ./gradlew   assemble --stacktrace
script:
  - TERM=dumb ./gradlew clean build --stacktrace
  - TERM=dumb $GRADLE -p samples clean check -x codenarcMain -x codenarcTest
  - TERM=dumb $GRADLE -p samples codenarcMain codenarcTest
notifications:
  email: false
branches:
  only:
    - master
    - develop
